rules:
  semi:
    - error
    - never
extends:
  - airbnb
  - plugin:jest/recommended
  - eslint:recommended
  - plugin:promise/recommended
plugins:
  - promise
  - jest
  - import
  - vue
  - react
env:
  es6: true
  node: true
  jest: true
