# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn workspaces run install
      - run: yarn lint
      - run: yarn test
      - run: cd server && docker build -t chaosd:${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  workflow:
    jobs:
      - build