# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: |
          yarn workspaces run install
          yarn lint
          yarn test

      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t chaosd:$TAG .      

workflows:
  version: 2
  workflow:
    jobs:
      - build