# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: node:10
    working_directory: ~/repo
    steps:
      - checkout

      - run: |
          yarn workspaces run install
          yarn lint
          yarn test

      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build & Push Control Plane
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            cd control-plane/api
            docker build -t chaosd/control-plane:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push chaosd/control-plane:$TAG
      
      - run:
          name: Build & Push AWS Gremlin
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            cd gremlins/aws/lambda
            docker build -t chaosd/gremlin-aws-lambda:$TAG .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push chaosd/gremlin-aws-lambda:$TAG

workflows:
  version: 2
  workflow:
    jobs:
      - build